import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css"
import UNavBar from "@/components/user/UNavBar";
import axios from "axios";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
axios.defaults.baseURL = "http://localhost:3000";
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="main-container">
          <div className="navbar">
            <UNavBar />
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
