import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css"
import UNavBar from "@/components/user/UNavBar";
import axios from "axios";
import AuthSession from "@/lib/AuthSession";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const {session} = await AuthSession()
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="main-container">
          <div className="navbar">
            <UNavBar user={session} />
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
