import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../app/globals.css";
import ReactQueryProvider from "@/utils/ReactQueryProvider";
import UNavBar from "@/components/user/UNavBar";
import AuthProvider from "@/utils/NextAuthConfig/AuthProvider";
import axios from "axios";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
axios.defaults.baseURL = 'http://localhost:3000';
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <AuthProvider >
      <ReactQueryProvider>
        <body className={inter.className}>
          <div className="main-container">
            <div className="navbar">
              <UNavBar />
            </div>
            {children}
          </div>
        </body>
      </ReactQueryProvider>
      </AuthProvider>
    </html>
  );
}
