import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../app/globals.css";
import ReactQueryProvider from "@/utils/ReactQueryProvider";
import UNavBar from "@/components/user/UNavBar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactQueryProvider>
        <body className={inter.className}>
          <div className="main-container">
            <div className="navbar">
              <UNavBar />
            </div>
          {children}
          </div>
          </body>
      </ReactQueryProvider>
    </html>
  );
}
