import SideBar from "@/components/admin/SideBar";
import type { Metadata } from "next";
import "../globals.css";
import NavBar from "@/components/admin/NavBar";
export const metadata: Metadata = {
  title: "admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex">
          <div className="shadow-md">
            <SideBar />
          </div>
          <div className="w-full  ">
            <div className="">
              <NavBar />
            </div>
            <div className="mt-[-1rem] flex w-full flex-col">
              <div className="divider h-[1px] bg-gray-300"></div>
            </div>
            <div className=" ">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
