import SideBar from "@/components/admin/SideBar";
import type { Metadata } from "next";
import "../globals.css";
import NavBar from "@/components/admin/NavBar";
export const metadata: Metadata = {
  title: "admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="  grid  grid-cols-3   ">
          <div className="bborder grid-cols-1 ">
            <SideBar />
          </div>
          <div className="bborder col-span-2">
            <div className=" ">
              <NavBar />
            </div>
            <div className=" ">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
